# Generated by Django 3.2.7 on 2021-11-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='color',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='genre',
            field=models.CharField(default='theatrical', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='materials',
            field=models.CharField(default='mixed', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='rate',
            field=models.CharField(default='$100', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='sizing',
            field=models.CharField(default='n/a', max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='type',
            field=models.CharField(default='shirt', max_length=250),
            preserve_default=False,
        ),
    ]
